// GENERATED by scripts/build.py - do not edit by hand.
// Only hashes ship here, never plaintext answers.
export const STAGE_HASHES = [
  {
    "hash": "4b89a5742ad3cecf47a75be161237882ec46ee3c986b17f45e06ab831bbf3716",
    "next": "stage-1-4b89a574/index.html"
  },
  {
    "hash": "7d4d29d8f0dbe51176455d9cd76cd4473ed97d4293284bd95392e1c24b1684d9",
    "next": "stage-2-7d4d29d8/index.html"
  },
  {
    "hash": "0c4f0c157c3df2dd154f6eb8d032a8d372ca5d95681c2e1811d181efc978054e",
    "next": "stage-3-0c4f0c15/index.html"
  },
  {
    "hash": "30ba504404e36f50898064b2c3b5c4866eb69fac458494a4245dc136d7e7b877",
    "next": "stage-4-30ba5044/index.html"
  },
  {
    "hash": "ecd24d4cda5e37c77322075d11dbcbe2d4d60d6fcda9a1a7d344c0c58ccaac54",
    "next": "stage-5-ecd24d4c/index.html"
  },
  {
    "hash": "b29082d48d8a2e4b2bfbe9075979a896952504453df1e8487fa08b6eae006ae7",
    "next": "stage-6-b29082d4/index.html"
  },
  {
    "hash": "092c79e8f80e559e404bcf660c48f3522b67aba9ff1484b0367e1a4ddef7431d",
    "next": "stage-7-092c79e8/index.html"
  },
  {
    "hash": "0f65cba03e132bdda00bfbb08e76bc16bce741ddd4c0c27c31623f44f20bf0f0",
    "next": "stage-8-0f65cba0/index.html"
  },
  {
    "hash": "1084664b6dfd560659c0942a88018fdb496e430910629d736c506a6e6970be5d",
    "next": "stage-9-1084664b/index.html"
  }
];
