"""Build script for the cicada-bday puzzle site."""

from __future__ import annotations

import base64
import hashlib
import json
import re
import shutil
import subprocess
import sys
import unicodedata
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from general_trivia import GENERAL_TRIVIA

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "templates"
CONTENT_DROP = ROOT / "content-drop"
ASSETS = ROOT / "assets"
LIB = ROOT / "lib"
PYTHON = sys.executable

VIGENERE_KEYWORD = "PRESENT"


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def answer_hash(text: str) -> str:
    return sha256_hex(normalize(text))


def strip_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(c for c in normalized if not unicodedata.combining(c))


def caesar_encrypt(text: str, shift: int) -> str:
    out = []
    for ch in text:
        if ch.isalpha():
            base = ord("A") if ch.isupper() else ord("a")
            out.append(chr((ord(ch) - base + shift) % 26 + base))
        else:
            out.append(ch)
    return "".join(out)


def vigenere_encrypt(plaintext: str, key: str) -> str:
    clean_key = re.sub(r"[^A-Z]", "", key.upper())
    if not clean_key:
        raise ValueError("Vigenere key must contain letters")
    a = ord("A")
    out = []
    key_index = 0
    for ch in plaintext.upper():
        if "A" <= ch <= "Z":
            shift = ord(clean_key[key_index % len(clean_key)]) - a
            out.append(chr((ord(ch) - a + shift) % 26 + a))
            key_index += 1
        else:
            out.append(ch)
    return "".join(out)


def render(template_name: str, tokens: dict) -> str:
    text = (TEMPLATES / template_name).read_text()
    for key, value in tokens.items():
        text = text.replace("{{" + key + "}}", value)
    remaining = re.findall(r"{{\s*[A-Z0-9_]+\s*}}", text)
    if remaining:
        raise ValueError(f"{template_name}: unfilled tokens {remaining}")
    return text


def run_script(name: str, *args: str) -> None:
    subprocess.run(
        [PYTHON, str(Path(__file__).parent / name), *args],
        check=True,
        cwd=ROOT,
    )


def load_secrets() -> dict:
    path = CONTENT_DROP / "secrets.json"
    if not path.exists():
        sys.exit(
            "content-drop/secrets.json not found. Copy secrets.example.json "
            "to secrets.json and fill it in first."
        )
    return json.loads(path.read_text())


def main() -> None:
    secrets = load_secrets()

    her_name = secrets.get("her_name", "").strip()
    greeting = (
        f"Joyeux anniversaire, {her_name}"
        if her_name
        else "Joyeux anniversaire"
    )
    her_name_or_you = her_name if her_name else "Toi"

    initial_pass = secrets["initial_passphrase"]
    pass1 = secrets["stage1_nickname"]
    poem_lines = secrets["stage2_poem_plain"]
    pass2 = strip_accents(poem_lines[-1])
    pass3 = secrets["stage3_message"]
    pass4 = secrets["stage4_message"]
    pass5 = secrets["stage5_message"]
    pass6 = secrets["stage6_word"]
    pass7 = secrets["city_zip"]
    pass8 = secrets["stage8_message"]
    final_plain = secrets["vigenere_final_plaintext"]

    met_year_shift = int(secrets["met_year"]) % 26
    ciphertext_lines = [
        caesar_encrypt(strip_accents(line), met_year_shift)
        for line in poem_lines
    ]
    stage2_ciphertext = "\n".join(ciphertext_lines)

    stage3_b64 = base64.b64encode(pass3.encode()).decode()
    stage5_b64 = base64.b64encode(pass5.encode()).decode()
    stage8_b64 = base64.b64encode(pass8.encode()).decode()
    stage9_ciphertext = vigenere_encrypt(final_plain, VIGENERE_KEYWORD)
    final_hash = answer_hash(final_plain)

    passphrases = [
        initial_pass,
        pass1,
        pass2,
        pass3,
        pass4,
        pass5,
        pass6,
        pass7,
        pass8,
    ]
    hashes = [answer_hash(p) for p in passphrases]
    hash8s = [h[:8] for h in hashes]

    stage_dirs = {n: f"stage-{n}-{hash8s[n - 1]}" for n in range(1, 10)}

    # ---- lib/stages.js (public hash -> next-page map) ----
    entries = []
    for n in range(1, 10):
        entries.append(
            {"hash": hashes[n - 1], "next": f"{stage_dirs[n]}/index.html"}
        )
    stages_js = (
        "// GENERATED by scripts/build.py - do not edit by hand.\n"
        "// Only hashes ship here, never plaintext answers.\n"
        "export const STAGE_HASHES = " + json.dumps(entries, indent=2) + ";\n"
    )
    (LIB / "stages.js").write_text(stages_js)

    # ---- clean old stage/finale dirs, then rebuild ----
    for d in ROOT.glob("stage-*-*"):
        if d.is_dir():
            shutil.rmtree(d)
    for d in ROOT.glob("finale-*"):
        if d.is_dir():
            shutil.rmtree(d)

    def write_page(dirname: str, html: str) -> None:
        out_dir = ROOT / dirname
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(html)

    write_page(
        stage_dirs[1],
        render(
            "stage1.html",
            {
                "NICKNAME": pass1,
                "GREETING": greeting,
                "HER_NAME_OR_YOU": her_name_or_you,
            },
        ),
    )
    write_page(
        stage_dirs[2],
        render("stage2.html", {"STAGE2_CIPHERTEXT": stage2_ciphertext}),
    )
    write_page(
        stage_dirs[3], render("stage3.html", {"STAGE3_BASE64": stage3_b64})
    )
    write_page(stage_dirs[4], render("stage4.html", {}))
    write_page(
        stage_dirs[5],
        render(
            "stage5.html",
            {
                "TRIVIA_JSON": json.dumps(GENERAL_TRIVIA),
                "STAGE5_MESSAGE_B64": stage5_b64,
            },
        ),
    )
    write_page(stage_dirs[6], render("stage6.html", {}))
    write_page(stage_dirs[7], render("stage7.html", {}))
    target_score = int(secrets.get("snake_target_score", 28))
    write_page(
        stage_dirs[8],
        render(
            "stage8.html",
            {
                "STAGE8_MESSAGE_B64": stage8_b64,
                "TARGET_SCORE": str(target_score),
            },
        ),
    )
    write_page(
        stage_dirs[9],
        render(
            "stage9.html",
            {
                "STAGE9_CIPHERTEXT": stage9_ciphertext,
                "STAGE9_CIPHERTEXT_JS": json.dumps(stage9_ciphertext),
                "FINAL_PLAINTEXT_HASH": final_hash,
            },
        ),
    )

    (ROOT / "index.html").write_text(render("index.html", {}))

    # ---- generated assets ----
    stage1_source = CONTENT_DROP / "stage1-photo.jpg"
    if stage1_source.exists():
        shutil.copy(stage1_source, ASSETS / "stage1-photo.jpg")
    else:
        run_script(
            "gen_placeholder_photo.py", str(ASSETS / "stage1-photo.jpg")
        )

    stage4_source_args = ["--message", pass4]
    for candidate in ("sancy.jpg", "couple-photo.jpg"):
        candidate_path = CONTENT_DROP / candidate
        if candidate_path.exists():
            stage4_source_args += ["--source", str(candidate_path)]
            break
    run_script("gen_stage4_photo.py", *stage4_source_args)

    spectrogram_args = [pass6, str(ASSETS / "stage6-audio.wav")]
    song_path = CONTENT_DROP / "stage6-song.wav"
    if song_path.exists():
        spectrogram_args += ["--source-audio", str(song_path)]
        if "stage6_song_clip_start_seconds" in secrets:
            spectrogram_args += [
                "--clip-start",
                str(secrets["stage6_song_clip_start_seconds"]),
            ]
        if "stage6_song_clip_duration_seconds" in secrets:
            spectrogram_args += [
                "--clip-duration",
                str(secrets["stage6_song_clip_duration_seconds"]),
            ]
    run_script("gen_spectrogram_wav.py", *spectrogram_args)

    city_name = secrets["city_name"]
    if city_name.strip().lower() == "charenton-le-pont":
        run_script(
            "gen_charenton_map.py", str(ASSETS / "stage7-epicycloid.gif")
        )
    else:
        run_script(
            "gen_epicycloid_gif.py",
            city_name,
            str(ASSETS / "stage7-epicycloid.gif"),
        )

    # ---- private answer key (gitignored) ----
    answers_md = [
        "# ANSWERS (private - do not commit, do not share)\n",
        "Regenerate this file any time with `python scripts/build.py`.\n",
        f"\n0. Portal starting word (tell her out loud/by text): `{initial_pass}`",
        f"1. Stage 1 -> Stage 2 answer: `{pass1}`  (folder: {stage_dirs[1]} / {stage_dirs[2]})",
        f"2. Stage 2 -> Stage 3 answer: `{pass2}`  (Caesar shift = met_year % 26 = {met_year_shift}, met_year = {secrets['met_year']})",
        f"3. Stage 3 -> Stage 4 answer: `{pass3}`",
        f"4. Stage 4 -> Stage 5 answer: `{pass4}`",
        f"5. Stage 5 -> Stage 6 answer: `{pass5}`",
        f"6. Stage 6 -> Stage 7 answer: `{pass6}`",
        f"7. Stage 7 -> Stage 8 answer (zip of {secrets['city_name']}): `{pass7}`",
        f"8. Stage 8 -> Stage 9 answer: `{pass8}`",
        f"9. Vigenere keyword (assembled letters): `{VIGENERE_KEYWORD}`",
        f"   Stage 9 ciphertext: {stage9_ciphertext}",
        f"   Decrypts to (this is the end of the site): {final_plain}",
    ]
    (ROOT / "ANSWERS.md").write_text("\n".join(answers_md) + "\n")

    testing_md = f"""# TESTING.md (private - gitignored, do not publish)

This walks through solving the whole chain start to finish, to confirm
it's wired up correctly. Kept out of git on purpose: committing this to
a public repo would hand out every answer.

## 0. Portal (index.html)
Type `{initial_pass}` into the box. Redirects to `{stage_dirs[1]}/`.

## 1. Stage 1 - the birthday card
View source (or inspect the hidden `.secret-nickname` span's `::after`
CSS content) to find `{pass1}`. Type it into the portal on this page.
-> `{stage_dirs[2]}/`

## 2. Stage 2 - Caesar cipher
Shift every letter of the ciphertext back by {met_year_shift}
(the year you met, {secrets["met_year"]}, mod 26). Accents were
stripped before encoding. Last decoded line is `{pass2}`.
-> `{stage_dirs[3]}/`

## 3. Stage 3 - console.log
Open devtools console. Base64 string decodes (via `atob(...)`) to
`{pass3}`.
-> `{stage_dirs[4]}/`

## 4. Stage 4 - EXIF photo
Click "Reveal what it remembers" on the page (reads the EXIF
UserComment tag client-side). Reveals `{pass4}`.
-> `{stage_dirs[5]}/`

## 5. Stage 5 - trivia
Answer 7 in a row correctly (general knowledge). On win, page shows
`{pass5}`.
-> `{stage_dirs[6]}/`

## 6. Stage 6 - spectrogram
Download the WAV, open in Audacity, switch the track to Spectrogram
view. It spells `{pass6}`.
-> `{stage_dirs[7]}/`

## 7. Stage 7 - epicycloid GIF
The rotating circles trace {secrets["city_name"]}'s real administrative
border (accurate GeoJSON), with the Seine and Bois de Vincennes shown
for context. The answer is that city's zip/postal code: `{pass7}`.
-> `{stage_dirs[8]}/`

## 8. Stage 8 - Snake
Score exactly {target_score}. Modal reveals `{pass8}`.
-> `{stage_dirs[9]}/`

## 9. Stage 9 - Vigenere (this is the last stage, no finale page)
Assemble the keyword from one letter hidden in each of stages 2-8
(filenames of the small doodle images + a matching HTML comment):
stage 2 -> P, stage 3 -> R, stage 4 -> E, stage 5 -> S, stage 6 -> E,
stage 7 -> N, stage 8 -> T = `{VIGENERE_KEYWORD}`.
Typing that key into the box on Stage 9 live-decrypts the ciphertext.
Once it matches, a box appears showing the final message:
"{final_plain}"
That's the end of the site - whatever real-world action this message
points to happens outside it.
"""
    (ROOT / "TESTING.md").write_text(testing_md)

    print("Build complete.")
    print(f"Portal starting word: {initial_pass}")


if __name__ == "__main__":
    main()
